// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillBuilder.Data;

#nullable disable

namespace SkillBuilder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250626034452_ConfigureCourseModel")]
    partial class ConfigureCourseModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillBuilder.Models.AboutFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Detailed learning paths from beginner to professional levels in traditional and contemporary art forms.",
                            IconPath = "/assets/Icons/Course.ico",
                            Title = "Structured Course"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Share insights, feedback, and experiences with fellow learners and master artisans.",
                            IconPath = "/assets/Icons/Community.ico",
                            Title = "Community Engagement"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Scheduled real-time query sessions with course instructor for personalized guidance.",
                            IconPath = "/assets/Icons/Sessions.ico",
                            Title = "Live Sessions"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Download courses for offline learning, ensuring accessibility regardless of internet connectivity.",
                            IconPath = "/assets/Icons/Download.ico",
                            Title = "Offline Access"
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SkillBuilder.Models.Artisan", b =>
                {
                    b.Property<string>("ArtisanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hometown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ArtisanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Artisans");

                    b.HasData(
                        new
                        {
                            ArtisanId = "A1111111",
                            FirstName = "Juan",
                            Hometown = "Vigan, Ilocos Sur",
                            Introduction = "Juan is a 3rd-generation artisan teaching pottery for 15 years.",
                            LastName = "Dela Cruz",
                            Profession = "Pottery Artisan",
                            Role = "Artisan",
                            UserAvatar = "/assets/Mentors/juan.png",
                            UserId = "A1111111"
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.ArtisanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutArtisan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hometown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ArtisanApplications");
                });

            modelBuilder.Entity("SkillBuilder.Models.ArtisanWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtisanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtisanId");

                    b.ToTable("ArtisanWorks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtisanId = "A1111111",
                            Caption = "Handcraft Pottery",
                            ImageUrl = "/assets/Works/JuanWorks1.png"
                        },
                        new
                        {
                            Id = 2,
                            ArtisanId = "A1111111",
                            Caption = "Clay Pot",
                            ImageUrl = "/assets/Works/JuanWorks2.png"
                        },
                        new
                        {
                            Id = 3,
                            ArtisanId = "A1111111",
                            Caption = "Pot Elegant",
                            ImageUrl = "/assets/Works/JuanWorks3.png"
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.CommunityHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Comments")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommunityHighlights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "/assets/Avatar/Sample1.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet.",
                            Comments = 36,
                            Image = "/assets/Community Pics/CompletePottery.png",
                            Likes = 128,
                            Name = "Maria Santos",
                            Role = "Learner"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "/assets/Avatar/Sample9.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet.",
                            Comments = 18,
                            Image = "/assets/Community Pics/CompleteWeaving.png",
                            Likes = 89,
                            Name = "James dela Cruz",
                            Role = "Artisan"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "/assets/Avatar/Sample5.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet.",
                            Comments = 41,
                            Image = "/assets/Community Pics/CompleteWoodcarving.png",
                            Likes = 212,
                            Name = "Kim Navarro",
                            Role = "Researcher"
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.CommunityPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("CommunityPosts");
                });

            modelBuilder.Entity("SkillBuilder.Models.CommunityTestimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommunityTestimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "/assets/Avatar/Sample1.ico",
                            Comment = "Our platform addresses the urgent need to preserve Philippine cultural and traditional art skills that are at risk of disappearing due to modernization.",
                            Role = "Learner",
                            UserName = "Maria Santos"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "/assets/Avatar/Sample2.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt. Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor.",
                            Role = "Researcher",
                            UserName = "Denise Velasco"
                        },
                        new
                        {
                            Id = 3,
                            AvatarPath = "/assets/Avatar/Sample3.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt.",
                            Role = "Artisan",
                            UserName = "Pamela Cruz"
                        },
                        new
                        {
                            Id = 4,
                            AvatarPath = "/assets/Avatar/Sample4.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor aaa aaa aaa  incididunt lorem ipsum dolor sit.",
                            Role = "Artisan",
                            UserName = "Angela Tiz"
                        },
                        new
                        {
                            Id = 5,
                            AvatarPath = "/assets/Avatar/Sample5.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt. Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor.",
                            Role = "Artisan",
                            UserName = "Marlene Qul"
                        },
                        new
                        {
                            Id = 6,
                            AvatarPath = "/assets/Avatar/Sample6.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur.",
                            Role = "Artisan",
                            UserName = "Brad Kiminda"
                        },
                        new
                        {
                            Id = 7,
                            AvatarPath = "/assets/Avatar/Sample7.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt. Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor.",
                            Role = "Artisan",
                            UserName = "Michael Ramirez"
                        },
                        new
                        {
                            Id = 8,
                            AvatarPath = "/assets/Avatar/Sample8.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on aa aa aa aa adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod.",
                            Role = "Artisan",
                            UserName = "Ella Parilla"
                        },
                        new
                        {
                            Id = 9,
                            AvatarPath = "/assets/Avatar/Sample9.ico",
                            Comment = "Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem .   aaa aaa aa aaa aa aa aa aa  ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor incididunt. Lorem ipsum dolor sit amet, consectetur on adipiscing elit, eiusmod tempor.",
                            Role = "Artisan",
                            UserName = "James Dawg"
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatToLearn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classes = "Pottery",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "A1111111",
                            Description = "Pottery is the art and craft of shaping and firing clay to create objects like bowls, plates, and decorative items.",
                            Duration = "15 hours",
                            FullDescription = "This course provides a step-by-step guide to both traditional and modern methods of pottery. From preparing your clay to understanding kiln temperatures and finishing your work with beautiful glazes, this course is perfect for anyone interested in the craft of ceramics.",
                            ImageUrl = "/assets/Courses Pics/Pottery.png",
                            IsPublished = false,
                            Level = "Beginner",
                            Link = "pottery",
                            ProjectDetails = "You'll complete a personal project: creating a glazed bowl or cup using wheel-throwing techniques.",
                            Requirements = "Clay, a pottery wheel or hand-building tools, access to a kiln, apron, and sponges.",
                            Thumbnail = "/assets/Courses Pics/Pottery.png",
                            Title = "Pottery",
                            Video = "/assets/Videos/Pottery.mp4",
                            WhatToLearn = "You'll learn pottery basics, hand-building, wheel throwing, and glazing techniques."
                        },
                        new
                        {
                            Id = 2,
                            Classes = "Wood Carving",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "A1111111",
                            Description = "Woodcarving is the art of shaping and sculpting wood into decorative or functional objects.",
                            Duration = "29 hours",
                            FullDescription = "Explore the detailed world of woodcarving through this course. You'll understand wood grain, learn safe carving practices, and master techniques to transform blocks of wood into detailed figurines, signs, and functional items. Ideal for artists or hobbyists.",
                            ImageUrl = "/assets/Courses Pics/Woodcarving.png",
                            IsPublished = false,
                            Level = "Intermediate",
                            Link = "woodcarving",
                            ProjectDetails = "Create your own carved decorative panel or wooden sculpture using techniques learned throughout the modules.",
                            Requirements = "Carving knives, gouges, mallet, sandpaper, safety gloves, and carving wood (basswood recommended).",
                            Thumbnail = "/assets/Courses Pics/Woodcarving.png",
                            Title = "Woodcarving",
                            Video = "/assets/Videos/Wood Carving.mp4",
                            WhatToLearn = "You'll learn carving techniques like relief carving, whittling, chip carving, and finishing."
                        },
                        new
                        {
                            Id = 3,
                            Classes = "Weaving",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "A1111111",
                            Description = "Weaving is the craft of interlacing threads or fibers to create fabric, textiles, or decorative art.",
                            Duration = "18 hours",
                            FullDescription = "This advanced course in weaving introduces students to both traditional and experimental textile design. Through projects and demonstrations, you’ll master loom warping, color theory in weaving, and understand how weaving traditions influence contemporary fiber arts.",
                            ImageUrl = "/assets/Courses Pics/Weaving.png",
                            IsPublished = false,
                            Level = "Professional",
                            Link = "weaving",
                            ProjectDetails = "You’ll complete a full-sized tapestry or wearable woven piece using your own pattern and chosen materials.",
                            Requirements = "Table or floor loom, warp and weft yarns, weaving comb, shuttles, and scissors.",
                            Thumbnail = "/assets/Courses Pics/Weaving.png",
                            Title = "Weaving",
                            Video = "/assets/Videos/Weaving.mp4",
                            WhatToLearn = "You’ll explore techniques in tapestry weaving, loom setup, fiber selection, and pattern creation."
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.CourseModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("SkillBuilder.Models.CourseProjectSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseProjectSubmissions");
                });

            modelBuilder.Entity("SkillBuilder.Models.CourseReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "An excellent course! The mentor was very knowledgeable.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = "A1111111"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Really enjoyed learning pottery. A few lessons were a bit fast though.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = "A1111111"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Very hands-on and engaging! Perfect for intermediate learners.",
                            CourseId = 3,
                            CreatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = "A1111111"
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SkillBuilder.Models.ModuleProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseModuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("ModuleProgress");
                });

            modelBuilder.Entity("SkillBuilder.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedInterests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAvatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("/assets/Avatar/Sample10.svg");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "A1111111",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "juan@example.com",
                            FirstName = "Juan",
                            IsVerified = true,
                            LastName = "Dela Cruz",
                            PasswordHash = "hashedpw",
                            Role = "Learner",
                            UserAvatar = "/assets/Avatar/Sample10.svg"
                        });
                });

            modelBuilder.Entity("SkillBuilder.Models.Admin", b =>
                {
                    b.HasOne("SkillBuilder.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBuilder.Models.Artisan", b =>
                {
                    b.HasOne("SkillBuilder.Models.User", "User")
                        .WithOne("Artisan")
                        .HasForeignKey("SkillBuilder.Models.Artisan", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBuilder.Models.ArtisanApplication", b =>
                {
                    b.HasOne("SkillBuilder.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBuilder.Models.ArtisanWork", b =>
                {
                    b.HasOne("SkillBuilder.Models.Artisan", "Artisan")
                        .WithMany("Works")
                        .HasForeignKey("ArtisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artisan");
                });

            modelBuilder.Entity("SkillBuilder.Models.CommunityPost", b =>
                {
                    b.HasOne("SkillBuilder.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SkillBuilder.Models.Course", b =>
                {
                    b.HasOne("SkillBuilder.Models.Artisan", "Artisan")
                        .WithMany("Courses")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artisan");
                });

            modelBuilder.Entity("SkillBuilder.Models.CourseModule", b =>
                {
                    b.HasOne("SkillBuilder.Models.Course", "Course")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SkillBuilder.Models.CourseProjectSubmission", b =>
                {
                    b.HasOne("SkillBuilder.Models.Course", "Course")
                        .WithMany("ProjectSubmissions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillBuilder.Models.User", "User")
                        .WithMany("ProjectSubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBuilder.Models.CourseReview", b =>
                {
                    b.HasOne("SkillBuilder.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillBuilder.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBuilder.Models.Enrollment", b =>
                {
                    b.HasOne("SkillBuilder.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillBuilder.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBuilder.Models.ModuleProgress", b =>
                {
                    b.HasOne("SkillBuilder.Models.CourseModule", "CourseModule")
                        .WithMany("Progresses")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillBuilder.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseModule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillBuilder.Models.Artisan", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("SkillBuilder.Models.Course", b =>
                {
                    b.Navigation("CourseModules");

                    b.Navigation("Enrollments");

                    b.Navigation("ProjectSubmissions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SkillBuilder.Models.CourseModule", b =>
                {
                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("SkillBuilder.Models.User", b =>
                {
                    b.Navigation("Artisan")
                        .IsRequired();

                    b.Navigation("Enrollments");

                    b.Navigation("ProjectSubmissions");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
